- name: prime-cache-3821d88
  uses: actions/cache@v4
  id: cache-deps
  with:
    path: |
      ~/.cache/pip
      ~/.local/lib/python3.11/site-packages
    key: cache-3821d88
    restore-keys: cache-3821d88
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
    save-always: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.13/x64
